backend:
  name: git-gateway
  branch: main
media_folder: "_site/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "components"
    label: "components"
    files:
      - name: "info"
        label: "Info"
        file: "src/_data/info.json"
        fields:
          - { label: "name", name: "name", widget: string }
          - { label: "email", name: "email", widget: string }
      - name: "navbar"
        label: "Navbar"
        file: "src/_data/navbar.json"
        fields:
          - { label: "brand", name: "brand", widget: string }
          - {
              label: "Logo",
              name: "logo",
              widget: "image",
              required: false,
              hint: "If not specified, Brand will be used as a text link",
            }
          - name: "navigations"
            label: "navigations"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
      - name: "footer"
        label: "footer"
        file: "src/_data/footer.json"
        fields:
          - {
              label: "Logo",
              name: "logo",
              widget: "image",
              required: false,
              hint: "If not specified, Brand will be used as a text link",
            }
          - { name: "subheading", label: "subheading", widget: "string" }
          - { name: "copyright", label: "copyright", widget: "string" }
          - name: "navigations"
            label: "navigations"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
          - name: "recht"
            label: "recht"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
          - name: "socials"
            label: "socials"
            widget: "list"
            fields:
              - { name: "url", label: "url", widget: "string" }
              - { name: "navigation", label: "navigation", widget: "string" }
      - name: "hero"
        label: "hero"
        file: "src/_data/hero.json"
        fields:
          - { label: "Hero Heading", name: "hero_heading", widget: "string" }
          - { label: "Hero Subheading", name: "hero_sub", widget: "string" }
          - { label: "Hero Button", name: "hero_btn", widget: "string" }
      - name: "benefits"
        label: "benefits"
        file: "src/_data/benefits.json"
        fields:
          - { label: "dummy", name: "dummy", widget: hidden }
          - name: "benefit"
            label: "benefit"
            widget: "list"
            fields:
              - { name: "icon", label: "icon", widget: "string" }
              - { name: "benefit_title", label: "Benefit Title", widget: "string" }
              - { name: "benefit_text", label: "Benefit Text", widget: "string" }
  - name: "projekte"
    label: "Projekte"
    folder: "src/projekte"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Card Heading", name: "card_heading", widget: "string" }
      - { label: "Card Subheading", name: "card_sub", widget: "string" }
      - { label: "Card Description", name: "card_desc", widget: "string" }
      - {
          label: "Card Image",
          name: "card_img",
          widget: "image",
          required: true,
        }
  - name: "blogposts"
    label: "Blogposts"
    folder: "src/blogposts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Card Heading", name: "card_heading", widget: "string" }
      - { label: "Card Subheading", name: "card_sub", widget: "string" }
      - { label: "Card Description", name: "card_desc", widget: "string" }
      - {
          label: "Card Image",
          name: "card_img",
          widget: "image",
          required: true,
        }
  - label: "Pages"
    name: "pages"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/index.html"
        fields:
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/home.html",
            }
          - { label: Title, name: title, widget: string }
      - name: "projekte"
        label: "projekte"
        file: "src/projekte.html"
        fields:
          - { label: Title, name: title, widget: string, default: "Projekte" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/projekte.html",
            }
      - name: "blog"
        label: "blog"
        file: "src/blog.html"
        fields:
          - { label: Title, name: title, widget: string, default: "blog" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/blog.html",
            }
      - name: "kontakt"
        label: "kontakt"
        file: "src/kontakt.html"
        fields:
          - { label: Title, name: title, widget: string, default: "kontakt" }
          - {
              label: Layout,
              name: "layout",
              widget: "hidden",
              default: "layouts/kontakt.html",
            }

